### ISSUE TITLE
Build issue: mpich@develop on m1 mac

### ISSUE THREAD

**Issue by s-sajid-ali** [pmodels/mpich#6166]
I'm seeing the following error when building mpich@develop on an M1 Mac: 

```
...
 >> 9470    ld64.lld: error: undefined symbol: _MPI_Comm_create_keyval
     9471    >>> referenced by initcxx.cxx:505 (src/binding/cxx/initcxx.cxx:505)
     9472    >>>               src/binding/cxx/.libs/initcxx.o:(symbol MPI::Comm::Create_keyval(int (*)(MPI::Comm const&, int, void*, void*, void*, bool&), 
             int (*)(MPI::Comm&, int, void*, void*), void*)+0x34)
     9473    
  >> 9474    ld64.lld: error: undefined symbol: _MPI_Comm_test_inter
     9475    >>> referenced by initcxx.cxx:474 (src/binding/cxx/initcxx.cxx:474)
     9476    >>>               src/binding/cxx/.libs/initcxx.o:(symbol MPI::MPII_Comm_copy_attr_cxx_proxy(int (*)(int, int, void*, void*, void*, int*), int,
              int, void*, MPI::MPIR_Attr_type, void*, void**, int*)+0x7c)
     9477    >>> referenced by initcxx.cxx:421 (src/binding/cxx/initcxx.cxx:421)
     9478    >>>               src/binding/cxx/.libs/initcxx.o:(symbol MPI::MPIR_Comm_delete_attr_cxx_proxy(int (*)(int, int, void*, void*), int, int, MPI::
             MPIR_Attr_type, void*, void*)+0x6c)
     9479    >>> referenced by initcxx.cxx:655 (src/binding/cxx/initcxx.cxx:655)
     9480    >>>               src/binding/cxx/.libs/initcxx.o:(symbol _MPIR_Call_errhandler_function+0x3c)
     9481    >>> referenced 1 more times
     9482    
  >> 9483    ld64.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
  >> 9484    clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

This error does not occur when I disable the cxx bindings, but I do require the mpicxx compiler wrapper. Is there a way to get the compiler wrapper without the c++ bindings?

Complete build logs for failing build with spack are here : [spack-logs.tar.gz](https://github.com/pmodels/mpich/files/9529353/spack-logs.tar.gz)

The compiler configuration for `clang@15.0.0` is :
```
- compiler:
    spec: clang@15.0.0
    paths:
      cc: /Users/sasyed/Documents/packages/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/llvm-15.0.0-qdzhugfypv4zwaohwyb7x7suixkffyp2/bin/clang
      cxx: /Users/sasyed/Documents/packages/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/llvm-15.0.0-qdzhugfypv4zwaohwyb7x7suixkffyp2/bin/clang++
      f77: /Users/sasyed/Documents/packages/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/llvm-15.0.0-qdzhugfypv4zwaohwyb7x7suixkffyp2/bin/flang-new
      fc: /Users/sasyed/Documents/packages/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/llvm-15.0.0-qdzhugfypv4zwaohwyb7x7suixkffyp2/bin/flang-new
    flags:
      cflags: -g -O2 -march=native -mtune=native --sysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
      cppflags: -g -O2 -march=native --sysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
      cxxflags: -g -O2 -march=native -mtune=native -stdlib=libc++ --sysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
      ldflags: -fuse-ld=lld -L /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
    operating_system: monterey
    target: aarch64
    modules: []
    environment: 
      prepend_path:
        LDFLAGS: -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
        CFLAGS: --sysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
    extra_rpaths:
      - /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
      - /Users/sasyed/Documents/packages/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/llvm-15.0.0-qdzhugfypv4zwaohwyb7x7suixkffyp2/lib
```
